[workspace]
resolver = "3"
members = [
    "crates/activator",
    "crates/protocol",
    "crates/protocol-diff",
    "zygisk",
]
exclude = ["lsposed/native"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"

[profile.dev]
opt-level = 1
panic = "abort"
